### ISSUE TITLE
AttributeError: 'list' object has no attribute 'split' while calling About.dumps()

### ISSUE THREAD

**Issue by tdruez** [aboutcode-org/aboutcode-toolkit#433]
Using `pip install aboutcode-toolkit==4.0.2`

I'm using the About class to generate ABOUT files calling the toolkit internal API from Python:

```
from attributecode.model import About

package_data = {
    'about_resource': 'package1.zip',
    'name': 'package',
    'version': '1.0',
    'copyright': 'copyright on package',
    'license_expression': 'license1 AND license2',
    'notice_file': 'package1.zip.NOTICE',
    'licenses': [
        {'key': 'license1', 'name': 'License1', 'file': 'license1.LICENSE'},
        {'key': 'license2', 'name': 'License2', 'file': 'license2.LICENSE'},
    ],
}

about = About()
about.load_dict(package_data, base_dir='')

>>> about.dumps()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "lib/python3.6/site-packages/attributecode/model.py", line 1036, in dumps
    license_file = field.original_value.split('\n')
AttributeError: 'list' object has no attribute 'split'
```

Note that this code was working fine with `aboutcode-toolkit==3.4.0rc1`
